{
 "title": "CPU_monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(cpu_usage)", "legendFormat": "{{process}}" }
   ]
  },
  {
   "title": "Average CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 0 },
   "targets": [
    { "expr": "avg(cpu_usage)", "legendFormat": "{{process}}" }
   ]
  },
  {
   "title": "Process consumption history",
   "type": "graph",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "topk(10, cpu_usage)" }
   ]
  },
  {
   "title": "Top 10 processes",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    { "expr": "topk(10, cpu_usage)" }
   ]
  }
 ]
}